update packages
choctaw-nation/landing pull request #273
Opened 2024-12-04 20:37 UTC by kjroelke

2024-12-05 18:08 UTC, blake-perkins-dev requested changes
https://choctawlandev.wpengine.com/things-to-do and https://choctawlandstg.wpengine.com/things-to-do - both don't have an Events feed on the page to review (they were in draft). I undrafted them and none have images, so I can't review this.

2024-12-05 18:10 UTC, kjroelke commented
Well that sucks. 

I'll copy the env down

2024-12-05 18:11 UTC, blake-perkins-dev commented
> Well that sucks.
> 
> I'll copy the env down

Even with adding an image, I can't see anything on the page. Just a green line
<img width="1137" alt="Screenshot 2024-12-05 at 12 10 54 PM" src="https://github.com/user-attachments/assets/3bd6c3b5-164c-4522-a188-0c8fa4af6c21">

2024-12-05 19:32 UTC, kjroelke commented
@blake-perkins-dev ready for review on https://choctawlandstg.wpengine.com/events

2024-12-05 22:01 UTC, blake-perkins-dev commented
I know this is going to be the most ridiculous feedback. Can you make the aspect ratio 33/50? This seems to be what it's using for most of the images.

Please use this for both the Events and the Things To Do page.

2024-12-06 20:12 UTC, blake-perkins-dev approved these changes
This looks so good! 10/10

2024-12-06 20:12 UTC, blake-perkins-dev commented on wp-content/themes/choctaw-landing/src/styles/components/_event-preview.scss
> +		aspect-ratio: 33 / 50;
Noice! 👌

2024-12-06 20:26 UTC, merged